# pispot — unified Makefile
#
# All build targets run on the Mac. Deployment targets ship artifacts
# to the Pi over SSH. Ansible targets configure the Pi OS.
#
# Quick start:
#   make init            — interactive first-time setup wizard
#   make deploy-all      — full stack deploy (authd + dashboard)

# ---------------------------------------------------------------------------
# Environment / secrets
# ---------------------------------------------------------------------------
# Load .env from the dashboard directory if it exists. This file is
# generated by `make init` and contains PI_HOST, PISPOT_TLS_CERT_NAME,
# and DASHBOARD_TITLE. It is gitignored.
-include dashboard/.env

PI_HOST            ?= $(error PI_HOST not set — run 'make init' first)
PISPOT_TLS_CERT_NAME ?= $(error PISPOT_TLS_CERT_NAME not set — run 'make init' first)
DASHBOARD_TITLE    ?= pispot

# ---------------------------------------------------------------------------
# Build identity
# ---------------------------------------------------------------------------
COMMIT     := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
DIRTY      := $(shell test -z "$$(git status --porcelain 2>/dev/null)" && echo false || echo true)
BUILD_TIME := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)

# ---------------------------------------------------------------------------
# Dashboard image
# ---------------------------------------------------------------------------
IMAGE          := pispot-ui:latest
PLATFORM       := linux/arm64
COMPOSE_FILE   := dashboard/docker-compose.yml
COMPOSE_PROJECT := pispot-ui

BUILDINFO_PKG := github.com/mcs-net/pispot/dashboard/internal/buildinfo
LDFLAGS_DASHBOARD := -s -w \
    -X $(BUILDINFO_PKG).Commit=$(COMMIT) \
    -X $(BUILDINFO_PKG).Dirty=$(DIRTY) \
    -X $(BUILDINFO_PKG).BuildTime=$(BUILD_TIME)

# ---------------------------------------------------------------------------
# Host binaries
# ---------------------------------------------------------------------------
GOOS_PI    := linux
GOARCH_PI  := arm64
CGO_ENABLED := 0
LDFLAGS_HOST := -s -w

AUTHD_PKG  := ./host/cmd/pispot-authd
AUTHD_OUT  := host/files/pispot-authd

PISPOTCTL_PKG := ./host/cmd/pispotctl
PISPOTCTL_OUT := host/files/pispotctl

# ---------------------------------------------------------------------------
# JS files for syntax checking
# ---------------------------------------------------------------------------
JS_FILES := $(wildcard dashboard/internal/web/static/*.js)

# ---------------------------------------------------------------------------
# Phony targets
# ---------------------------------------------------------------------------
.PHONY: all build build-dashboard build-authd build-pispotctl \
        test vet fmt js-check tidy \
        docker-build image-size \
        ship-dashboard restart-dashboard \
        deploy-authd _deploy-authd-no-setup deploy-dashboard deploy-all \
        bootstrap setup checkup \
        init gen-certs check-secrets \
        logs ssh clean help

all: build

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
build: build-dashboard build-authd build-pispotctl

## build-dashboard: compile pispot-ui locally (Mac-native, for syntax checks)
build-dashboard:
	go build -trimpath -ldflags="$(LDFLAGS_DASHBOARD)" \
	    -o bin/pispot-ui ./dashboard/cmd/pispot-ui

## build-authd: cross-compile pispot-authd for linux/arm64 → host/files/
build-authd:
	go clean -cache
	GOOS=$(GOOS_PI) GOARCH=$(GOARCH_PI) CGO_ENABLED=$(CGO_ENABLED) \
	    go build -trimpath -ldflags="$(LDFLAGS_HOST)" \
	    -o $(AUTHD_OUT) $(AUTHD_PKG)
	@echo "built $(AUTHD_OUT)"

## build-pispotctl: cross-compile pispotctl for linux/arm64 → host/files/
build-pispotctl:
	GOOS=$(GOOS_PI) GOARCH=$(GOARCH_PI) CGO_ENABLED=$(CGO_ENABLED) \
	    go build -trimpath -ldflags="$(LDFLAGS_HOST)" \
	    -o $(PISPOTCTL_OUT) $(PISPOTCTL_PKG)
	@echo "built $(PISPOTCTL_OUT)"

# ---------------------------------------------------------------------------
# Test / lint
# ---------------------------------------------------------------------------
test:
	go test ./...

vet:
	go vet ./...

fmt:
	gofmt -w .

tidy:
	go mod tidy

## js-check: syntax-check all embedded JS files via node --check
js-check:
	@for f in $(JS_FILES); do \
	  node --check $$f && echo "ok $$f" || exit 1; \
	done

# ---------------------------------------------------------------------------
# Docker
# ---------------------------------------------------------------------------
## docker-build: build pispot-ui:latest image for linux/arm64
docker-build:
	docker build --platform $(PLATFORM) \
	    --build-arg COMMIT=$(COMMIT) \
	    --build-arg DIRTY=$(DIRTY) \
	    --build-arg BUILD_TIME=$(BUILD_TIME) \
	    -f dashboard/Dockerfile \
	    -t $(IMAGE) .

## image-size: print the size of the local pispot-ui image
image-size:
	@docker image inspect $(IMAGE) --format '{{.Size}}' 2>/dev/null \
	    | awk '{printf "%.1f MB\n", $$1/1024/1024}' \
	    || echo "image not built"

# ---------------------------------------------------------------------------
# Deploy — dashboard
# ---------------------------------------------------------------------------
## ship-dashboard: save + gzip + ssh + docker load image onto Pi
ship-dashboard: check-secrets
	docker save $(IMAGE) | gzip | ssh $(PI_HOST) 'gunzip | docker load'

## restart-dashboard: pipe compose over SSH, up -d --no-build
restart-dashboard: check-secrets
	ssh $(PI_HOST) \
	    'PISPOT_TLS_CERT_NAME=$(PISPOT_TLS_CERT_NAME) DASHBOARD_TITLE="$(DASHBOARD_TITLE)" \
	    docker compose --project-name $(COMPOSE_PROJECT) -f - up -d --no-build' \
	    < $(COMPOSE_FILE)

## deploy-dashboard: docker-build + ship-dashboard + restart-dashboard
deploy-dashboard: js-check docker-build ship-dashboard restart-dashboard

# ---------------------------------------------------------------------------
# Deploy — authd
# ---------------------------------------------------------------------------
## deploy-authd: build-authd + build-pispotctl + Ansible pi-setup.yml
deploy-authd: build-authd build-pispotctl
	ansible-playbook -i ansible/inventory/hosts ansible/pi-setup.yml --ask-become-pass

## _deploy-authd-no-setup: build binaries only, no Ansible (used by deploy-all)
_deploy-authd-no-setup: build-authd build-pispotctl

# ---------------------------------------------------------------------------
# Deploy — full stack
# ---------------------------------------------------------------------------
## deploy-all: build + setup + ship authd + ship dashboard (full stack, disruptive)
deploy-all: check-secrets
	@printf "This will deploy the full stack to $(PI_HOST) and restart all services.\n"
	@printf "Active dashboard users will be disconnected briefly.\n"
	@printf "Continue? [y/N] " && read ans && [ "$${ans:-N}" = y ]
	$(MAKE) _deploy-authd-no-setup
	$(MAKE) setup
	$(MAKE) deploy-dashboard

# ---------------------------------------------------------------------------
# Ansible
# ---------------------------------------------------------------------------
## bootstrap: apt upgrade + base packages + wifi country (run once on fresh Pi)
bootstrap:
	ansible-playbook -i ansible/inventory/hosts ansible/pi-bootstrap.yml --ask-become-pass

## setup: full OS configuration (dhcpcd, hostapd, dnsmasq, nftables, pispot-authd)
setup:
	ansible-playbook -i ansible/inventory/hosts ansible/pi-setup.yml --ask-become-pass

## checkup: read-only health check — validates IP forwarding, services, DNS
checkup:
	ansible-playbook -i ansible/inventory/hosts ansible/pi-checkup.yml --ask-become-pass

# ---------------------------------------------------------------------------
# Init / first-time setup
# ---------------------------------------------------------------------------
## init: interactive first-time setup wizard (generates dashboard/.env)
init:
	python3 scripts/init.py

## gen-certs: generate self-signed TLS certs for local testing
gen-certs:
	@mkdir -p ssl
	@echo "Generating self-signed test cert (10 years, CN=pispot.local)..."
	openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
	    -keyout ssl/test_cert.key \
	    -out ssl/test_cert.crt \
	    -subj "/CN=pispot.local" \
	    -addext "subjectAltName=DNS:pispot.local,IP:10.10.10.1"
	cp ssl/test_cert.crt ssl/test_cert.ca
	@echo ""
	@echo "Generated:"
	@echo "  ssl/test_cert.crt  (certificate + CA bundle)"
	@echo "  ssl/test_cert.key  (private key)"
	@echo "  ssl/test_cert.ca   (CA cert — copy of .crt for self-signed)"
	@echo ""
	@echo "Set PISPOT_TLS_CERT_NAME=test_cert in dashboard/.env to use these."

## check-secrets: verify required secret files and config exist before deploy
check-secrets:
	@python3 scripts/check_secrets.py

# ---------------------------------------------------------------------------
# Pi management
# ---------------------------------------------------------------------------
## logs: ssh to Pi and run pispotctl logs
logs:
	ssh $(PI_HOST) sudo pispotctl logs

## ssh: open an SSH session to the Pi
ssh:
	ssh $(PI_HOST)

# ---------------------------------------------------------------------------
# Clean
# ---------------------------------------------------------------------------
clean:
	rm -rf bin
	rm -f $(AUTHD_OUT) $(PISPOTCTL_OUT)

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------
help:
	@echo "pispot — available make targets"
	@echo ""
	@echo "Build:"
	@echo "  build              Build everything (dashboard + authd + pispotctl)"
	@echo "  build-dashboard    Compile pispot-ui locally (Mac-native, syntax check)"
	@echo "  build-authd        Cross-compile pispot-authd for linux/arm64"
	@echo "  build-pispotctl    Cross-compile pispotctl for linux/arm64"
	@echo ""
	@echo "Test:"
	@echo "  test               Run all Go tests"
	@echo "  js-check           Syntax-check embedded JS via node --check"
	@echo "  vet                go vet ./..."
	@echo "  fmt                gofmt -w ."
	@echo ""
	@echo "Docker:"
	@echo "  docker-build       Build pispot-ui:latest image (linux/arm64)"
	@echo "  image-size         Print local image size"
	@echo ""
	@echo "Deploy:"
	@echo "  ship-dashboard     Save + gzip + ssh + docker load image onto Pi"
	@echo "  restart-dashboard  Pipe compose over SSH, up -d --no-build"
	@echo "  deploy-dashboard   docker-build + ship-dashboard + restart-dashboard"
	@echo "  deploy-authd       build-authd + build-pispotctl + Ansible pi-setup"
	@echo "  deploy-all         build + setup + deploy authd + deploy dashboard (full stack)"
	@echo ""
	@echo "Ansible:"
	@echo "  bootstrap          apt upgrade + packages (run once on fresh Pi)"
	@echo "  setup              Full OS configuration"
	@echo "  checkup            Read-only health check"
	@echo ""
	@echo "Init / first-time:"
	@echo "  init               Interactive setup wizard (generates dashboard/.env)"
	@echo "  gen-certs          Generate self-signed test TLS certs via OpenSSL"
	@echo "  check-secrets      Verify required secrets exist before deploy"
	@echo ""
	@echo "Pi management:"
	@echo "  logs               SSH to Pi and run pispotctl logs"
	@echo "  ssh                Open SSH session to Pi"
	@echo ""
	@echo "  clean              Remove build artifacts"
