#!/usr/bin/env python3
"""
pispot first-time setup wizard.

Generates:
  dashboard/.env              — PI_HOST, PISPOT_TLS_CERT_NAME, DASHBOARD_TITLE
  ansible/inventory/hosts     — [pi] section with ansible_host and ansible_user
  ansible/group_vars/all.yml  — wifi_country, hotspot creds, wan_networks,
                                pispot_https_hostname, pispot_tls_cert_name,
                                dashboard_title

Run with: make init

On re-run, existing values are read back from the generated files and
offered as defaults, so only changed fields need to be re-entered.
"""

import re
import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DASHBOARD_ENV = REPO_ROOT / "dashboard" / ".env"
INVENTORY = REPO_ROOT / "ansible" / "inventory" / "hosts"
GROUP_VARS = REPO_ROOT / "ansible" / "group_vars" / "all.yml"


# ---------------------------------------------------------------------------
# Loaders — read back previously generated files
# ---------------------------------------------------------------------------

def load_env(path: Path) -> dict:
    """Parse a simple KEY=VALUE .env file. Returns {} if file absent."""
    out = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def load_group_vars(path: Path) -> dict:
    """
    Parse the subset of group_vars/all.yml we generate.

    We only need simple scalar values and the wan_networks list — no
    general YAML parser required. Returns {} if file absent.
    """
    out: dict = {}
    if not path.exists():
        return out

    text = path.read_text()

    # Simple scalars: key: "value"  or  key: value
    for key in (
        "wifi_country", "hotspot_ssid", "hotspot_password",
        "pispot_https_hostname", "pispot_tls_cert_name", "dashboard_title",
    ):
        m = re.search(rf'^{re.escape(key)}:\s*"?([^"\n]+)"?\s*$', text, re.MULTILINE)
        if m:
            out[key] = m.group(1).strip()

    # wan_networks list: pairs of ssid / password lines
    networks = []
    for m in re.finditer(
        r'^\s{2}-\s+ssid:\s+"?([^"\n]+)"?\s*\n\s{4}password:\s+"?([^"\n]+)"?',
        text,
        re.MULTILINE,
    ):
        networks.append({"ssid": m.group(1).strip(), "password": m.group(2).strip()})
    if networks:
        out["wan_networks"] = networks

    # ansible_user from inventory/hosts
    if INVENTORY.exists():
        m = re.search(r'ansible_user=(\S+)', INVENTORY.read_text())
        if m:
            out["ansible_user"] = m.group(1)

    return out


# ---------------------------------------------------------------------------
# UI helpers
# ---------------------------------------------------------------------------

def ask(prompt: str, default: str = "", secret: bool = False) -> str:
    """Prompt for a value; return default if the user presses Enter."""
    display = f"{prompt} [{default}]: " if default else f"{prompt}: "
    if secret:
        import getpass
        value = getpass.getpass(display).strip()
    else:
        value = input(display).strip()
    return value if value else default


def ask_required(prompt: str, default: str = "", secret: bool = False) -> str:
    """Prompt until a non-empty value is provided."""
    while True:
        value = ask(prompt, default=default, secret=secret)
        if value:
            return value
        print("  (required — please enter a value)")


def section(title: str, subtitle: str = "") -> None:
    print(f"\n{'─' * 60}")
    print(f"  {title}")
    if subtitle:
        print(f"  - {subtitle}")
    print(f"{'─' * 60}")


# ---------------------------------------------------------------------------
# YAML builder
# ---------------------------------------------------------------------------

def yq(value: str) -> str:
    return f'"{value}"'


def build_group_vars(
    *,
    wifi_country: str,
    hotspot_ssid: str,
    hotspot_password: str,
    wan_networks: list,
    https_hostname: str,
    tls_cert_name: str,
    dashboard_title: str,
) -> str:
    lines = [
        "# Generated by make init — do not commit.",
        "",
        f"wifi_country: {yq(wifi_country)}",
        "",
        f"hotspot_ssid: {yq(hotspot_ssid)}",
        f"hotspot_password: {yq(hotspot_password)}",
        "",
        "wan_networks:",
    ]
    for n in wan_networks:
        lines.append(f"  - ssid: {yq(n['ssid'])}")
        lines.append(f"    password: {yq(n['password'])}")
    lines += [
        "",
        f"pispot_https_hostname: {yq(https_hostname)}",
        f"pispot_tls_cert_name: {yq(tls_cert_name)}",
        f"dashboard_title: {yq(dashboard_title)}",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print()
    print("pispot setup wizard")
    print("=" * 60)

    # Load existing values so re-runs pre-populate defaults.
    prev_env = load_env(DASHBOARD_ENV)
    prev_vars = load_group_vars(GROUP_VARS)

    rerun = bool(prev_env or prev_vars)
    if rerun:
        print("Existing config detected — press Enter to keep current values.")
    else:
        print("This wizard generates config files for your pispot deployment.")
        print("Your answers are saved locally and are gitignored.")
    print()

    # ------------------------------------------------------------------
    # Pi connection
    # ------------------------------------------------------------------
    section("Pi connection", "used for SSH, Ansible setup, and make ssh/logs/deploy targets")
    pi_host = ask_required(
        "Pi hostname or IP",
        default=prev_env.get("PI_HOST", ""),
    )
    ansible_user = ask(
        "SSH username on the Pi",
        default=prev_vars.get("ansible_user", "pi"),
    )

    # ------------------------------------------------------------------
    # Dashboard
    # ------------------------------------------------------------------
    section("Dashboard")
    dashboard_title = ask(
        "Dashboard page title",
        default=prev_env.get("DASHBOARD_TITLE") or prev_vars.get("dashboard_title", "pispot"),
    )

    # ------------------------------------------------------------------
    # TLS certificate
    # ------------------------------------------------------------------
    section("TLS certificate")
    print("  Place your .crt, .key, and .ca files in the ssl/ directory.")
    print("  The cert name is the filename prefix (without extension).")
    print("  Example: ssl/my_cert.crt → cert name is 'my_cert'")
    print()
    print("  To generate self-signed test certs instead: make gen-certs")
    print()
    tls_cert_name = ask_required(
        "TLS cert name (filename prefix in ssl/)",
        default=prev_env.get("PISPOT_TLS_CERT_NAME") or prev_vars.get("pispot_tls_cert_name", ""),
    )

    # ------------------------------------------------------------------
    # HTTPS hostname
    # ------------------------------------------------------------------
    section("HTTPS hostname")
    print("  The hostname used in the TLS cert and dnsmasq address record.")
    print("  Must resolve to 10.10.10.1 on the hotspot network.")
    https_hostname = ask(
        "HTTPS hostname",
        default=prev_vars.get("pispot_https_hostname", "pispot.local"),
    )

    # ------------------------------------------------------------------
    # Wi-Fi country
    # ------------------------------------------------------------------
    section("Wi-Fi country")
    wifi_country = ask(
        "Wi-Fi country code (ISO 3166-1 alpha-2)",
        default=prev_vars.get("wifi_country", "US"),
    )

    # ------------------------------------------------------------------
    # Hotspot credentials
    # ------------------------------------------------------------------
    section("Hotspot (wlan0) credentials")
    print("  SSID and password for the AP your clients connect to.")
    print()
    hotspot_ssid = ask_required(
        "Hotspot SSID",
        default=prev_vars.get("hotspot_ssid", ""),
    )
    hotspot_password = ask_required(
        "Hotspot password (min 8 chars)",
        default=prev_vars.get("hotspot_password", ""),
        secret=True,
    )
    while len(hotspot_password) < 8:
        print("  Password must be at least 8 characters.")
        hotspot_password = ask_required(
            "Hotspot password (min 8 chars)",
            default=prev_vars.get("hotspot_password", ""),
            secret=True,
        )

    # ------------------------------------------------------------------
    # WAN networks
    # ------------------------------------------------------------------
    section("WAN (wlan1) networks")
    print("  Upstream Wi-Fi networks the USB adapter connects to.")
    print("  Add at least one. Press Enter with a blank SSID to stop.")

    prev_wan = prev_vars.get("wan_networks", [])
    if prev_wan:
        print()
        print("  Current networks (re-enter to keep, or replace entirely):")
        for i, n in enumerate(prev_wan, 1):
            print(f"    {i}. {n['ssid']}")

    print()
    wan_networks = []
    i = 1
    # Pre-populate prompt defaults from previous run.
    while True:
        prev_ssid = prev_wan[i - 1]["ssid"] if i <= len(prev_wan) else ""
        ssid = ask(f"WAN network #{i} SSID (blank to finish)", default=prev_ssid)
        if not ssid:
            if not wan_networks:
                print("  (at least one WAN network is required)")
                continue
            break
        prev_psk = prev_wan[i - 1]["password"] if i <= len(prev_wan) else ""
        password = ask_required(
            f"  Password for '{ssid}'",
            default=prev_psk,
            secret=True,
        )
        while len(password) < 8:
            print("  Password must be at least 8 characters.")
            password = ask_required(
                f"  Password for '{ssid}'",
                default=prev_psk,
                secret=True,
            )
        wan_networks.append({"ssid": ssid, "password": password})
        i += 1

    # ------------------------------------------------------------------
    # Write files
    # ------------------------------------------------------------------
    section("Writing config files")

    # dashboard/.env
    env_lines = [
        "# Generated by make init — do not commit.",
        f"PI_HOST={pi_host}",
        f"PISPOT_TLS_CERT_NAME={tls_cert_name}",
        f"DASHBOARD_TITLE={dashboard_title}",
        "",
    ]
    DASHBOARD_ENV.write_text("\n".join(env_lines))
    print(f"  wrote {DASHBOARD_ENV.relative_to(REPO_ROOT)}")

    # ansible/inventory/hosts
    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    hosts_lines = [
        "# Generated by make init — do not commit.",
        "[pi]",
        f"pi-host ansible_host={pi_host} ansible_user={ansible_user}",
        "",
    ]
    INVENTORY.write_text("\n".join(hosts_lines))
    print(f"  wrote {INVENTORY.relative_to(REPO_ROOT)}")

    # ansible/group_vars/all.yml
    GROUP_VARS.parent.mkdir(parents=True, exist_ok=True)
    GROUP_VARS.write_text(build_group_vars(
        wifi_country=wifi_country,
        hotspot_ssid=hotspot_ssid,
        hotspot_password=hotspot_password,
        wan_networks=wan_networks,
        https_hostname=https_hostname,
        tls_cert_name=tls_cert_name,
        dashboard_title=dashboard_title,
    ))
    print(f"  wrote {GROUP_VARS.relative_to(REPO_ROOT)}")

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print()
    print("=" * 60)
    print("Setup complete.")
    print()
    print("Next steps:")
    print(f"  1. Place TLS files in ssl/:")
    print(f"       ssl/{tls_cert_name}.crt")
    print(f"       ssl/{tls_cert_name}.key")
    print(f"       ssl/{tls_cert_name}.ca")
    print(f"     (or run: make gen-certs  for self-signed test certs)")
    print()
    print(f"  2. Build binaries and Docker image:")
    print(f"       make build")
    print(f"       make docker-build")
    print()
    print(f"  3. Bootstrap the Pi (first time only):")
    print(f"       make bootstrap")
    print()
    print(f"  4. Deploy the full stack:")
    print(f"       make deploy-all")
    print()


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\n\nAborted.")
        sys.exit(1)
